sign-commit = true
upload-doc = true
pre-release-replacements = [
  {file="CHANGELOG.md", search="Unreleased", replace="{{version}}"},
  {file="CHANGELOG.md", search="ReleaseDate", replace="{{date}}"},
  {file="README.md", search="Current release: [a-z0-9\\.-]+", replace="Current release: {{version}}"},
]
