[package]
name = "ift-cli"
version = "0.1.0"
authors = ["Cameron Davison <cameron@novilabs.com>"]
edition = "2018"

[dependencies]
clap = "2.32.0"
ift = {path = "../ift/"}
error-chain = "0.12.0"

[dev-dependencies]
assert_cmd = "0.10.2"
predicates = "1.0.0"
